# Proto

permalink:           pretty


title: altis
description: "A blog for aezlo"
locale: en_GB
disqus: altis
paginate: 5

url: "athelo.net"
baseurl: '/altis'

author:
  name:              Aezlo
  url:               https://twitter.com/aethelo
  email:             admin@athelo.net

# Footer Links

footer-links:
  dribbble: #
  email: admin@athelo.net
  facebook: #
  flickr: #
  github: 2aezlo
  instagram: #
  linkedin: #
  pinterest: #
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
