# Proto

permalink:           pretty
relative_permalinks: true

title: altis
description: "A blog for aezlo"
locale: en_GB
disqus: altis
paginate: 5

url: "athelo.net"
baseurl: '/altis'

author:
  name:              Aezlo
  url:               https://twitter.com/aethelo
  email:             admin@athelo.net
